Scala version updated to 2.13.4. This is causing an out of memory error when compiling in Sbt, on Kubuntu 20.04 and Kubuntu 20.10.
Exception in thread "sbt-task-progress-report-thread" java.lang.OutOfMemoryError: Java heap space
Exception in thread "classloader-cache-cleanup-0" java.lang.OutOfMemoryError: Java heap space
	at sbt.internal.classpath.ClassLoaderCache$$Lambda$780/0x000000010066f040.get$Lambda(Unknown Source)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.Invokers$Holder.linkToTargetMethod(Invokers$Holder)
	at sbt.internal.classpath.ClassLoaderCache.sbt$internal$classpath$ClassLoaderCache$$clearExpiredLoaders(ClassLoaderCache.scala:79)
	at sbt.internal.classpath.ClassLoaderCache$CleanupThread.run(ClassLoaderCache.scala:113)
[error] ## Exception when compiling 93 sources to /Common/openstrat/SbtDir/UtilCore/target/scala-2.13/classes
[error] java.lang.OutOfMemoryError: Java heap space
[error]
[error]
[info] shutting down sbt server
java.lang.OutOfMemoryError: Java heap space
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space